version: '3'

services:
  llmai-writer:
    build: .
    container_name: llmai-writer
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
    volumes:
      - ./config.ini:/app/config.ini
      - ./novels:/app/novels
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    command: --dark  # 可选：启用深色模式
